# Generated by Django 3.1.2 on 2021-04-09 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone_number', models.CharField(blank=True, max_length=15, verbose_name='Phone Number')),
                ('user_neighborhood', models.CharField(blank=True, choices=[('Soho', 'Soho'), ('Tribeca', 'Tribeca')], max_length=20, verbose_name='Neighborhood')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeeTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tee_time_date', models.DateField(verbose_name='Date of Tee Time')),
                ('tee_time_course', models.CharField(choices=[('Pelham Bay', 'Pelham Bay')], max_length=30, verbose_name='Golf Course')),
                ('tee_time_users', models.ManyToManyField(related_name='user_tee_times', to='bt_site.UserProfile')),
            ],
        ),
    ]
