# Generated by Django 3.1.5 on 2021-02-03 07:43

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bt_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='None', max_length=9, verbose_name='Day of Week')),
                ('open_time', models.TimeField(verbose_name='Opening Time')),
                ('close_time', models.TimeField(verbose_name='Closing Time')),
            ],
        ),
        migrations.AddField(
            model_name='venue',
            name='venue_capacity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Venue Capacity'),
        ),
        migrations.AddField(
            model_name='venue',
            name='venue_sports',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bball', 'Basketball'), ('Soc.', 'Soccer'), ('Soft.', 'Softball')], default='None', max_length=16, verbose_name='Venue Sports'),
        ),
        migrations.AddField(
            model_name='venue',
            name='venue_type',
            field=models.CharField(choices=[('City', 'City Property'), ('School', 'School Property'), ('Rec.', 'Rec. Facility')], default='None', max_length=6, verbose_name='Venue Type'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_goals',
            field=models.CharField(choices=[('Comp.', 'Competition'), ('Soc.', 'Socializing')], default='Comp.', max_length=30, verbose_name='Group Tags'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Group Rating'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_type',
            field=models.CharField(choices=[('Pub.', 'Public'), ('Fr.', 'Friends Only'), ('Inv.', 'Invite Only')], default='Pub.', max_length=5, verbose_name='Group Type'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_badges',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Temp1', 'Badge 1'), ('Temp2', 'Badge 2')], default='None', max_length=30, verbose_name='Player Badges'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_birthday',
            field=models.DateField(default=0.0005, verbose_name='Player Birthday'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_location',
            field=models.CharField(default='None', max_length=30, verbose_name='Player Location'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Player Rating'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_sports',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bball', 'Basketball'), ('Soc.', 'Soccer'), ('Soft.', 'Softball')], default='None', max_length=16, verbose_name='Player Sports'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Comp.', 'Competition'), ('Soc.', 'Socializing')], default='None', max_length=30, verbose_name='Player Tags'),
        ),
    ]
