# Generated by Django 3.1.5 on 2021-02-03 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bt_site', '0002_auto_20210202_2343'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvailableHours',
            new_name='Availability',
        ),
    ]
